project:
  name: demo-service
server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: abc123456
    url: jdbc:mysql://ibyg.net:3306/test
    username: root
  redis:
    host: ibyg.net
    jedis:
      pool:
        max-idle: 8
        max-wait: ''
        min-idle: 0
    password: abc123456
    port: 6379
    timeout: 30000


dubbo:
  application:
    id: demo-service
    name: demo-service
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    serialization: hessian2
  registry:
    address: ibyg.net
    port: 2181
    protocol: zookeeper
  scan:
    basePackages: com.alibaba.demo
logging:
  file:
    name: /data/logs/demo-service/
